name: Release

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: alexcheng1982/jdk-debug    

permissions:
  contents: write

jobs:
  docker:
    name: docker
    concurrency:
      group: docker
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.IMAGE_NAME}}:latest,${{ env.IMAGE_NAME}}:${{ github.event.release.name }}
          context: .
          file: ./Dockerfile-jdk8
          build-args: JDK8_TAG=${{ github.event.release.name }}
          # platforms: linux/amd64, linux/arm64
          provenance: true
          sbom: true